### ISSUE TITLE
Publish new version to npm for the recent pull request

### ISSUE THREAD

**Issue by alexcfyung** [adaltas/node-krb5#18]
Can you guys publish a new version to npm to make the recent PR official? if not what are the restrictions?

**Comment by wdavidw** [comment]
I have tried to run it on OSX without success but I didn't had much time to dig the problem.

**Comment by alexcfyung** [comment]
Is this the issue you have on OSX?
```
 error: Exception support not detected. Define either NAPI_CPP_EXCEPTIONS or NAPI_DISABLE_CPP_EXCEPTIONS.
   #error Exception support not detected. \
    ^
1 error generated.
```
This issue seems to already exist before the pull request. It looks like it is caused by the NAPI_DISABLE_CPP_EXCEPTIONS not defined even `-fno-exceptions` is passed

**Comment by wdavidw** [comment]
This is my issue:

```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/wdavidw/n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:266:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/wdavidw/n/bin/node" "/Users/wdavidw/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wdavidw/projects/github/krb5
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
error Command failed with exit code 1.
```

However, the tests pass inside the docker-compose which means they are fine on Linux. @RReivax any idea, it would be cool to have osx working again, you told me a couple of weeks ago that it was expected to work.

**Comment by wdavidw** [comment]
Hi @alexcfyung, Sorry for the delay, I just pushed version 0.5.2. I still haven't make it worked on osx but all linux tests passed and I've got not feedback from @RReivax. Thank you for your great contribution
