### ISSUE TITLE
Error when running npm install on Windows 10

### ISSUE THREAD

**Issue by feenst** [adaltas/node-krb5#9]
I get the following error when trying to run `npm install` on Windows 10:
```
..\src\bind.cc(67): error C2466: cannot allocate an array of constant size 0
```

It's coming from [this line](https://github.com/adaltas/node-krb5/blob/master/src/bind.cc#L67) in bind.cc.
node-gyp is using the `Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64`.

Looks like there is varying support in compilers for zero-size arrays: https://stackoverflow.com/questions/9722632/what-happens-if-i-define-a-0-size-array-in-c-c

**Comment by wdavidw** [comment]
We are currently rewritting the binding to support the latest version of Node.js. Which version of Node.js are u using, if 8, try with 6 to confirm that the issue also apply with this version.

**Comment by feenst** [comment]
I'm running Node 6.10.2.

**Comment by vinnydu** [comment]
Hello. 
Are there any solution for this? 

At the moment as workaround I have to change row 71 of hades-krb5/rc/bind.cc file from:

`const int argc = 0;`
to:
`const int argc = 1;`

Thanks.

**Comment by SyntakSoftware** [comment]
Hi All,

I tried to run the npm install for the hbase project and received an error from the attempted compilation of this project (krb5).  I have cloned this project and tried the npm install directly on this project with the same error.

 I am running Windows 10 with Node v10.16.3 and npm 6.12.10 installing this to a Nestjs application.

I have the MIT Kerberos installed in the default location and have been able to fully compile the "npm install kerberos" project, so the set up for Windows compilation seems to be working.

The error is:
Microsoft Windows [Version 10.0.17134.1009]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\273008\source\repos\node-krb5>npm install
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to http://
registry.npmjs.org/coffeescript failed, reason: connect ETIMEDOUT 104.16.17.35:80
npm WARN registry Using stale data from http://registry.npmjs.org/ due to a request error during revalidation.

> krb5@0.5.1 install C:\Users\273008\source\repos\node-krb5
> node-gyp rebuild


C:\Users\273008\source\repos\node-krb5>if not defined npm_config_node_gyp (node "C:\Users\273008\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\273008\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\273008\source\repos\node-krb5\build\Release\\nothing.lib
  module.cc
  krb5_bind.cc
  gss_bind.cc
  base64.cc
  win_delay_load_hook.cc
c:\users\273008\source\repos\node-krb5\src\krb5_bind.h(7): fatal error C1083: Cannot open include file: 'unistd.h': No
such file or directory (compiling source file ..\src\module.cc) [C:\Users\273008\source\repos\node-krb5\build\krb5.vcxp
roj]
c:\users\273008\source\repos\node-krb5\src\krb5_bind.h(7): fatal error C1083: Cannot open include file: 'unistd.h': No
such file or directory (compiling source file ..\src\krb5_bind.cc) [C:\Users\273008\source\repos\node-krb5\build\krb5.v
cxproj]
c:\users\273008\source\repos\node-krb5\src\gss_bind.h(10): fatal error C1083: Cannot open include file: 'unistd.h': No
such file or directory (compiling source file ..\src\gss_bind.cc) [C:\Users\273008\source\repos\node-krb5\build\krb5.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\273008\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\273008\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\273008\source\repos\node-krb5
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! krb5@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the krb5@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\273008\AppData\Roaming\npm-cache\_logs\2019-10-14T14_48_55_077Z-debug.log

C:\Users\273008\source\repos\node-krb5>
C:\Users\273008\source\repos\node-krb5>


The "unistd.h" file is a Unix file and is not found on the Windows system.  Is there another step I missed perhaps?  Looks like there may be a couple of other Unix only header files included in some of the header files.  Is there a work around for Windows at this time?

Thanks a ton for any help!!
[2019-10-14T14_48_55_077Z-debug.log](https://github.com/adaltas/node-krb5/files/3725122/2019-10-14T14_48_55_077Z-debug.log)

**Comment by wdavidw** [comment]
@RReivax any idea ?

**Comment by royprigat** [comment]
@SyntakSoftware any updates? I am also running into the same issue

**Comment by himanshiGitHub** [comment]
I am facing same isssue with node version 12.2.0.

**Comment by MaciejTyrcha** [comment]
I managed to solve unistd.h and sys/syscall.h errors, but now im stuck to this (sorry for no english):


c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(12): error C2061: błąd składniowy: identyfikator "uint" [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(59): error C3646: "rlen": nieznany specyfikator przesłonięcia [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(59): error C4430: brak specyfikatora typu - założono, że int. Uwaga: C++ nie obsługuje domyślnie typu int [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(17): error C2065: "callback": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(18): error C2065: "rlen": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(18): error C2614: "Worker_krb5_build_principal": Niedozwolone inicjowanie składowej: "rlen" nie jest obiektem bazowym ani składową [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(32): error C2065: "rlen": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(41): error C2065: "rlen": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(75): error C2065: "uint": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(75): error C2146: błąd składniowy: brakuje ";" przed identyfikatorem "rlen" [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(75): error C2065: "rlen": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
c:\users\bbr.kerb.adm\desktop\kerberos node\libraries\krb5\src\krb5_bind.cc(82): error C2065: "rlen": niezadeklarowany identyfikator [C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5\build\krb5.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\BBR.KERB.adm\Desktop\Kerberos Node\Libraries\krb5
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

**Comment by wdavidw** [comment]
Hi Maciej, we don't work on Windows so we can't really help with this OS. @himanshiGitHub last time we built the package was probably with Node.js version 10.  @RReivax could you try to make it pass with a recent version of Node.js such as 14 ?

**Comment by himanshiGitHub** [comment]
Sure.

**Comment by Guillaume-Boutry** [comment]
Hi,

With PR #27, the windows build should be fixed.

We have a vagrant file setting up Windows VM (if you want to check the build tool necessary).

We also have a Github Action job building on Windows (no testing for now).

Closing this issue, don't hesitate to open another one if you have any issue.
